/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_BasebandProcessingCombi_r15_H_
#define	_BasebandProcessingCombi_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BP-InfoPerBandList-r15.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BasebandProcessingCombi-r15 */
typedef struct BasebandProcessingCombi_r15 {
	BP_InfoPerBandList_r15_t	 bp_InfoPerBandList;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasebandProcessingCombi_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasebandProcessingCombi_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_BasebandProcessingCombi_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_BasebandProcessingCombi_r15_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _BasebandProcessingCombi_r15_H_ */
#include <asn_internal.h>
