/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_BasebandParameters_r15_H_
#define	_BasebandParameters_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BasebandProcessingCombiList_r15;

/* BasebandParameters-r15 */
typedef struct BasebandParameters_r15 {
	struct BasebandProcessingCombiList_r15	*basebandProcessingCombiList_r15	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasebandParameters_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasebandParameters_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_BasebandParameters_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_BasebandParameters_r15_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BasebandProcessingCombiList-r15.h"

#endif	/* _BasebandParameters_r15_H_ */
#include <asn_internal.h>
