/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_BP_InfoPerBandList_r15_H_
#define	_BP_InfoPerBandList_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BP_InfoPerBand_r15;

/* BP-InfoPerBandList-r15 */
typedef struct BP_InfoPerBandList_r15 {
	A_SEQUENCE_OF(struct BP_InfoPerBand_r15) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BP_InfoPerBandList_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BP_InfoPerBandList_r15;
extern asn_SET_OF_specifics_t asn_SPC_BP_InfoPerBandList_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_BP_InfoPerBandList_r15_1[1];
extern asn_per_constraints_t asn_PER_type_BP_InfoPerBandList_r15_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BP-InfoPerBand-r15.h"

#endif	/* _BP_InfoPerBandList_r15_H_ */
#include <asn_internal.h>
