/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_BP_InfoPerBand_r15_H_
#define	_BP_InfoPerBand_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CA-BandwidthClass-r10.h"
#include "BW-PerCC-r15.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BP_InfoPerCC_r15;

/* BP-InfoPerBand-r15 */
typedef struct BP_InfoPerBand_r15 {
	CA_BandwidthClass_r10_t	 ca_BandwidthClassDL_r15;
	CA_BandwidthClass_r10_t	 ca_BandwidthClassUL_r15;
	struct BP_InfoPerBand_r15__bp_InfoPerCC_List_r15 {
		A_SEQUENCE_OF(struct BP_InfoPerCC_r15) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} bp_InfoPerCC_List_r15;
	BW_PerCC_r15_t	 supportedBandwidthPerCC_r15;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BP_InfoPerBand_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BP_InfoPerBand_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_BP_InfoPerBand_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_BP_InfoPerBand_r15_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BP-InfoPerCC-r15.h"

#endif	/* _BP_InfoPerBand_r15_H_ */
#include <asn_internal.h>
