/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#include "BP-InfoPerBand-r15.h"

static int
memb_bp_InfoPerCC_List_r15_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 32)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_bp_InfoPerCC_List_r15_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..32)) */};
static asn_per_constraints_t asn_PER_type_bp_InfoPerCC_List_r15_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_bp_InfoPerCC_List_r15_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..32)) */};
static asn_per_constraints_t asn_PER_memb_bp_InfoPerCC_List_r15_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 5,  5,  1,  32 }	/* (SIZE(1..32)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_bp_InfoPerCC_List_r15_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_BP_InfoPerCC_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_bp_InfoPerCC_List_r15_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_bp_InfoPerCC_List_r15_specs_4 = {
	sizeof(struct BP_InfoPerBand_r15__bp_InfoPerCC_List_r15),
	offsetof(struct BP_InfoPerBand_r15__bp_InfoPerCC_List_r15, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_bp_InfoPerCC_List_r15_4 = {
	"bp-InfoPerCC-List-r15",
	"bp-InfoPerCC-List-r15",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_bp_InfoPerCC_List_r15_tags_4,
	sizeof(asn_DEF_bp_InfoPerCC_List_r15_tags_4)
		/sizeof(asn_DEF_bp_InfoPerCC_List_r15_tags_4[0]) - 1, /* 1 */
	asn_DEF_bp_InfoPerCC_List_r15_tags_4,	/* Same as above */
	sizeof(asn_DEF_bp_InfoPerCC_List_r15_tags_4)
		/sizeof(asn_DEF_bp_InfoPerCC_List_r15_tags_4[0]), /* 2 */
	{ &asn_OER_type_bp_InfoPerCC_List_r15_constr_4, &asn_PER_type_bp_InfoPerCC_List_r15_constr_4, SEQUENCE_OF_constraint },
	asn_MBR_bp_InfoPerCC_List_r15_4,
	1,	/* Single element */
	&asn_SPC_bp_InfoPerCC_List_r15_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_BP_InfoPerBand_r15_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BP_InfoPerBand_r15, ca_BandwidthClassDL_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CA_BandwidthClass_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ca-BandwidthClassDL-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BP_InfoPerBand_r15, ca_BandwidthClassUL_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CA_BandwidthClass_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ca-BandwidthClassUL-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BP_InfoPerBand_r15, bp_InfoPerCC_List_r15),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_bp_InfoPerCC_List_r15_4,
		0,
		{ &asn_OER_memb_bp_InfoPerCC_List_r15_constr_4, &asn_PER_memb_bp_InfoPerCC_List_r15_constr_4,  memb_bp_InfoPerCC_List_r15_constraint_1 },
		0, 0, /* No default value */
		"bp-InfoPerCC-List-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BP_InfoPerBand_r15, supportedBandwidthPerCC_r15),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BW_PerCC_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedBandwidthPerCC-r15"
		},
};
static const ber_tlv_tag_t asn_DEF_BP_InfoPerBand_r15_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BP_InfoPerBand_r15_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ca-BandwidthClassDL-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ca-BandwidthClassUL-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* bp-InfoPerCC-List-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* supportedBandwidthPerCC-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_BP_InfoPerBand_r15_specs_1 = {
	sizeof(struct BP_InfoPerBand_r15),
	offsetof(struct BP_InfoPerBand_r15, _asn_ctx),
	asn_MAP_BP_InfoPerBand_r15_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BP_InfoPerBand_r15 = {
	"BP-InfoPerBand-r15",
	"BP-InfoPerBand-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_BP_InfoPerBand_r15_tags_1,
	sizeof(asn_DEF_BP_InfoPerBand_r15_tags_1)
		/sizeof(asn_DEF_BP_InfoPerBand_r15_tags_1[0]), /* 1 */
	asn_DEF_BP_InfoPerBand_r15_tags_1,	/* Same as above */
	sizeof(asn_DEF_BP_InfoPerBand_r15_tags_1)
		/sizeof(asn_DEF_BP_InfoPerBand_r15_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BP_InfoPerBand_r15_1,
	4,	/* Elements count */
	&asn_SPC_BP_InfoPerBand_r15_specs_1	/* Additional specs */
};

