/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#include "BP-InfoPerCC-r15.h"

asn_TYPE_member_t asn_MBR_BP_InfoPerCC_r15_1[] = {
	{ ATF_POINTER, 2, offsetof(struct BP_InfoPerCC_r15, supportedMIMO_CapabilityDL_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MIMO_CapabilityDL_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedMIMO-CapabilityDL-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct BP_InfoPerCC_r15, supportedMIMO_CapabilityUL_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MIMO_CapabilityUL_r10,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"supportedMIMO-CapabilityUL-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BP_InfoPerCC_r15, modulationOrder_r15),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ModulationOrder_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"modulationOrder-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct BP_InfoPerCC_r15, subCarrierSpacing),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubCarrierSpacingNR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subCarrierSpacing"
		},
};
static const int asn_MAP_BP_InfoPerCC_r15_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_BP_InfoPerCC_r15_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BP_InfoPerCC_r15_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* supportedMIMO-CapabilityDL-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* supportedMIMO-CapabilityUL-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* modulationOrder-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* subCarrierSpacing */
};
asn_SEQUENCE_specifics_t asn_SPC_BP_InfoPerCC_r15_specs_1 = {
	sizeof(struct BP_InfoPerCC_r15),
	offsetof(struct BP_InfoPerCC_r15, _asn_ctx),
	asn_MAP_BP_InfoPerCC_r15_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_BP_InfoPerCC_r15_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BP_InfoPerCC_r15 = {
	"BP-InfoPerCC-r15",
	"BP-InfoPerCC-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_BP_InfoPerCC_r15_tags_1,
	sizeof(asn_DEF_BP_InfoPerCC_r15_tags_1)
		/sizeof(asn_DEF_BP_InfoPerCC_r15_tags_1[0]), /* 1 */
	asn_DEF_BP_InfoPerCC_r15_tags_1,	/* Same as above */
	sizeof(asn_DEF_BP_InfoPerCC_r15_tags_1)
		/sizeof(asn_DEF_BP_InfoPerCC_r15_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BP_InfoPerCC_r15_1,
	4,	/* Elements count */
	&asn_SPC_BP_InfoPerCC_r15_specs_1	/* Additional specs */
};

