/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_BP_InfoPerCC_r15_H_
#define	_BP_InfoPerCC_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MIMO-CapabilityDL-r10.h"
#include "MIMO-CapabilityUL-r10.h"
#include "ModulationOrder-r15.h"
#include "SubCarrierSpacingNR-r15.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BP-InfoPerCC-r15 */
typedef struct BP_InfoPerCC_r15 {
	MIMO_CapabilityDL_r10_t	*supportedMIMO_CapabilityDL_r15	/* OPTIONAL */;
	MIMO_CapabilityUL_r10_t	*supportedMIMO_CapabilityUL_r15	/* OPTIONAL */;
	ModulationOrder_r15_t	 modulationOrder_r15;
	SubCarrierSpacingNR_r15_t	 subCarrierSpacing;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BP_InfoPerCC_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BP_InfoPerCC_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_BP_InfoPerCC_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_BP_InfoPerCC_r15_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _BP_InfoPerCC_r15_H_ */
#include <asn_internal.h>
