/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#include "FreqOffsetNR-r15.h"

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_FreqOffsetNR_r15_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
asn_TYPE_descriptor_t asn_DEF_FreqOffsetNR_r15 = {
	"FreqOffsetNR-r15",
	"FreqOffsetNR-r15",
	&asn_OP_NativeInteger,
	asn_DEF_FreqOffsetNR_r15_tags_1,
	sizeof(asn_DEF_FreqOffsetNR_r15_tags_1)
		/sizeof(asn_DEF_FreqOffsetNR_r15_tags_1[0]), /* 1 */
	asn_DEF_FreqOffsetNR_r15_tags_1,	/* Same as above */
	sizeof(asn_DEF_FreqOffsetNR_r15_tags_1)
		/sizeof(asn_DEF_FreqOffsetNR_r15_tags_1[0]), /* 1 */
	{ 0, 0, NativeInteger_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

