/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_MeasObjectNR_r15_H_
#define	_MeasObjectNR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueNR-r15.h"
#include "RS-IndexNR-r15.h"
#include "Q-OffsetRangeInterRAT.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RS_ConfigSSB_NR_r15;
struct ThresholdNR_r15;
struct CellIndexList;
struct CellsToAddModListNR;

/* MeasObjectNR-r15 */
typedef struct MeasObjectNR_r15 {
	ARFCN_ValueNR_r15_t	 carrierFreq_r15;
	struct RS_ConfigSSB_NR_r15	*rs_ConfigSSB_r15	/* OPTIONAL */;
	struct ThresholdNR_r15	*threshRS_Index_r15	/* OPTIONAL */;
	RS_IndexNR_r15_t	*maxRS_IndexCellQual_r15	/* OPTIONAL */;
	Q_OffsetRangeInterRAT_t	 offsetFreq_r15	/* DEFAULT 0 */;
	struct CellIndexList	*blackCellsToRemoveList_r15	/* OPTIONAL */;
	struct CellsToAddModListNR	*blackCellsToAddModList_r15	/* OPTIONAL */;
	long	 quantityConfigSet_r15;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasObjectNR_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasObjectNR_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasObjectNR_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasObjectNR_r15_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RS-ConfigSSB-NR-r15.h"
#include "ThresholdNR-r15.h"
#include "CellIndexList.h"
#include "CellsToAddModListNR.h"

#endif	/* _MeasObjectNR_r15_H_ */
#include <asn_internal.h>
