/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#include "MeasResultCellNR-r15.h"

asn_TYPE_member_t asn_MBR_MeasResultCellNR_r15_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultCellNR_r15, pci_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellIdNR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pci-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultCellNR_r15, measResultCell_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultNR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultCell-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultCellNR_r15, measResultRS_IndexList_r15),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MeasResultSSB_IndexList_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResultRS-IndexList-r15"
		},
};
static const int asn_MAP_MeasResultCellNR_r15_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_MeasResultCellNR_r15_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasResultCellNR_r15_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pci-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* measResultCell-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* measResultRS-IndexList-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasResultCellNR_r15_specs_1 = {
	sizeof(struct MeasResultCellNR_r15),
	offsetof(struct MeasResultCellNR_r15, _asn_ctx),
	asn_MAP_MeasResultCellNR_r15_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MeasResultCellNR_r15_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasResultCellNR_r15 = {
	"MeasResultCellNR-r15",
	"MeasResultCellNR-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasResultCellNR_r15_tags_1,
	sizeof(asn_DEF_MeasResultCellNR_r15_tags_1)
		/sizeof(asn_DEF_MeasResultCellNR_r15_tags_1[0]), /* 1 */
	asn_DEF_MeasResultCellNR_r15_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasResultCellNR_r15_tags_1)
		/sizeof(asn_DEF_MeasResultCellNR_r15_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasResultCellNR_r15_1,
	3,	/* Elements count */
	&asn_SPC_MeasResultCellNR_r15_specs_1	/* Additional specs */
};

