/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#include "MeasObjectNR-r15.h"

static int
memb_quantityConfigSet_r15_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_quantityConfigSet_r15_constr_9 CC_NOTUSED = {
	{ 1, 1 }	/* (1..2) */,
	-1};
static asn_per_constraints_t asn_PER_memb_quantityConfigSet_r15_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  1,  2 }	/* (1..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static int asn_DFL_6_cmp_0(const void *sptr) {
	const Q_OffsetRangeInterRAT_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 0 */
	return (*st != 0);
}
static int asn_DFL_6_set_0(void **sptr) {
	Q_OffsetRangeInterRAT_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 0 */
	*st = 0;
	return 0;
}
asn_TYPE_member_t asn_MBR_MeasObjectNR_r15_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasObjectNR_r15, carrierFreq_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ARFCN_ValueNR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"carrierFreq-r15"
		},
	{ ATF_POINTER, 6, offsetof(struct MeasObjectNR_r15, rs_ConfigSSB_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RS_ConfigSSB_NR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rs-ConfigSSB-r15"
		},
	{ ATF_POINTER, 5, offsetof(struct MeasObjectNR_r15, threshRS_Index_r15),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ThresholdNR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"threshRS-Index-r15"
		},
	{ ATF_POINTER, 4, offsetof(struct MeasObjectNR_r15, maxRS_IndexCellQual_r15),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RS_IndexNR_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maxRS-IndexCellQual-r15"
		},
	{ ATF_NOFLAGS, 3, offsetof(struct MeasObjectNR_r15, offsetFreq_r15),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Q_OffsetRangeInterRAT,
		0,
		{ 0, 0, 0 },
		&asn_DFL_6_cmp_0,	/* Compare DEFAULT 0 */
		&asn_DFL_6_set_0,	/* Set DEFAULT 0 */
		"offsetFreq-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct MeasObjectNR_r15, blackCellsToRemoveList_r15),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellIndexList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"blackCellsToRemoveList-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasObjectNR_r15, blackCellsToAddModList_r15),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellsToAddModListNR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"blackCellsToAddModList-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasObjectNR_r15, quantityConfigSet_r15),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_quantityConfigSet_r15_constr_9, &asn_PER_memb_quantityConfigSet_r15_constr_9,  memb_quantityConfigSet_r15_constraint_1 },
		0, 0, /* No default value */
		"quantityConfigSet-r15"
		},
};
static const int asn_MAP_MeasObjectNR_r15_oms_1[] = { 1, 2, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_MeasObjectNR_r15_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasObjectNR_r15_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* carrierFreq-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rs-ConfigSSB-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* threshRS-Index-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* maxRS-IndexCellQual-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* offsetFreq-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* blackCellsToRemoveList-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* blackCellsToAddModList-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* quantityConfigSet-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasObjectNR_r15_specs_1 = {
	sizeof(struct MeasObjectNR_r15),
	offsetof(struct MeasObjectNR_r15, _asn_ctx),
	asn_MAP_MeasObjectNR_r15_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_MeasObjectNR_r15_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	8,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasObjectNR_r15 = {
	"MeasObjectNR-r15",
	"MeasObjectNR-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasObjectNR_r15_tags_1,
	sizeof(asn_DEF_MeasObjectNR_r15_tags_1)
		/sizeof(asn_DEF_MeasObjectNR_r15_tags_1[0]), /* 1 */
	asn_DEF_MeasObjectNR_r15_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasObjectNR_r15_tags_1)
		/sizeof(asn_DEF_MeasObjectNR_r15_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasObjectNR_r15_1,
	8,	/* Elements count */
	&asn_SPC_MeasObjectNR_r15_specs_1	/* Additional specs */
};

