/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_MTC_SSB_NR_r15_H_
#define	_MTC_SSB_NR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MTC-SSB-NR-r15 */
typedef struct MTC_SSB_NR_r15 {
	long	 ssb_Timing_r15;
	long	 ssb_Duration_r15;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MTC_SSB_NR_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MTC_SSB_NR_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_MTC_SSB_NR_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_MTC_SSB_NR_r15_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MTC_SSB_NR_r15_H_ */
#include <asn_internal.h>
