/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#include "PDCP-ParametersNR-r15.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_rohc_ContextMaxSessions_r15_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_rohc_ContextMaxSessions_r15_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_rohc_ContextContinue_r15_constr_31 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_rohc_ContextContinue_r15_constr_31 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_outOfOrderDelivery_r15_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_outOfOrderDelivery_r15_constr_33 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_sn_SizeLo_r15_constr_35 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_sn_SizeLo_r15_constr_35 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_voice_r15_constr_37 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_voice_r15_constr_37 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 0,  0,  0,  0 }	/* (0..0) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_rohc_Profiles_r15_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0001_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0001-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0002_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0002-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0003_r15),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0003-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0004_r15),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0004-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0006_r15),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0006-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0101_r15),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0101-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0102_r15),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0102-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0103_r15),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0103-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, profile0x0104_r15),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0104-r15"
		},
};
static const ber_tlv_tag_t asn_DEF_rohc_Profiles_r15_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_rohc_Profiles_r15_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* profile0x0001-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* profile0x0002-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* profile0x0003-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* profile0x0004-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* profile0x0006-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* profile0x0101-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* profile0x0102-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* profile0x0103-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* profile0x0104-r15 */
};
static asn_SEQUENCE_specifics_t asn_SPC_rohc_Profiles_r15_specs_2 = {
	sizeof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15),
	offsetof(struct PDCP_ParametersNR_r15__rohc_Profiles_r15, _asn_ctx),
	asn_MAP_rohc_Profiles_r15_tag2el_2,
	9,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rohc_Profiles_r15_2 = {
	"rohc-Profiles-r15",
	"rohc-Profiles-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_rohc_Profiles_r15_tags_2,
	sizeof(asn_DEF_rohc_Profiles_r15_tags_2)
		/sizeof(asn_DEF_rohc_Profiles_r15_tags_2[0]) - 1, /* 1 */
	asn_DEF_rohc_Profiles_r15_tags_2,	/* Same as above */
	sizeof(asn_DEF_rohc_Profiles_r15_tags_2)
		/sizeof(asn_DEF_rohc_Profiles_r15_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_rohc_Profiles_r15_2,
	9,	/* Elements count */
	&asn_SPC_rohc_Profiles_r15_specs_2	/* Additional specs */
};

static int asn_DFL_12_cmp_4(const void *sptr) {
	const long *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 4 */
	return (*st != 4);
}
static int asn_DFL_12_set_4(void **sptr) {
	long *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 4 */
	*st = 4;
	return 0;
}
static const asn_INTEGER_enum_map_t asn_MAP_rohc_ContextMaxSessions_r15_value2enum_12[] = {
	{ 0,	3,	"cs2" },
	{ 1,	3,	"cs4" },
	{ 2,	3,	"cs8" },
	{ 3,	4,	"cs12" },
	{ 4,	4,	"cs16" },
	{ 5,	4,	"cs24" },
	{ 6,	4,	"cs32" },
	{ 7,	4,	"cs48" },
	{ 8,	4,	"cs64" },
	{ 9,	5,	"cs128" },
	{ 10,	5,	"cs256" },
	{ 11,	5,	"cs512" },
	{ 12,	6,	"cs1024" },
	{ 13,	7,	"cs16384" },
	{ 14,	6,	"spare2" },
	{ 15,	6,	"spare1" }
};
static const unsigned int asn_MAP_rohc_ContextMaxSessions_r15_enum2value_12[] = {
	12,	/* cs1024(12) */
	3,	/* cs12(3) */
	9,	/* cs128(9) */
	4,	/* cs16(4) */
	13,	/* cs16384(13) */
	0,	/* cs2(0) */
	5,	/* cs24(5) */
	10,	/* cs256(10) */
	6,	/* cs32(6) */
	1,	/* cs4(1) */
	7,	/* cs48(7) */
	11,	/* cs512(11) */
	8,	/* cs64(8) */
	2,	/* cs8(2) */
	15,	/* spare1(15) */
	14	/* spare2(14) */
};
static const asn_INTEGER_specifics_t asn_SPC_rohc_ContextMaxSessions_r15_specs_12 = {
	asn_MAP_rohc_ContextMaxSessions_r15_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_rohc_ContextMaxSessions_r15_enum2value_12,	/* N => "tag"; sorted by N */
	16,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_rohc_ContextMaxSessions_r15_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rohc_ContextMaxSessions_r15_12 = {
	"rohc-ContextMaxSessions-r15",
	"rohc-ContextMaxSessions-r15",
	&asn_OP_NativeEnumerated,
	asn_DEF_rohc_ContextMaxSessions_r15_tags_12,
	sizeof(asn_DEF_rohc_ContextMaxSessions_r15_tags_12)
		/sizeof(asn_DEF_rohc_ContextMaxSessions_r15_tags_12[0]) - 1, /* 1 */
	asn_DEF_rohc_ContextMaxSessions_r15_tags_12,	/* Same as above */
	sizeof(asn_DEF_rohc_ContextMaxSessions_r15_tags_12)
		/sizeof(asn_DEF_rohc_ContextMaxSessions_r15_tags_12[0]), /* 2 */
	{ &asn_OER_type_rohc_ContextMaxSessions_r15_constr_12, &asn_PER_type_rohc_ContextMaxSessions_r15_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rohc_ContextMaxSessions_r15_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_rohc_ProfilesUL_Only_r15_29[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15__rohc_ProfilesUL_Only_r15, profile0x0006_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profile0x0006-r15"
		},
};
static const ber_tlv_tag_t asn_DEF_rohc_ProfilesUL_Only_r15_tags_29[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_rohc_ProfilesUL_Only_r15_tag2el_29[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* profile0x0006-r15 */
};
static asn_SEQUENCE_specifics_t asn_SPC_rohc_ProfilesUL_Only_r15_specs_29 = {
	sizeof(struct PDCP_ParametersNR_r15__rohc_ProfilesUL_Only_r15),
	offsetof(struct PDCP_ParametersNR_r15__rohc_ProfilesUL_Only_r15, _asn_ctx),
	asn_MAP_rohc_ProfilesUL_Only_r15_tag2el_29,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rohc_ProfilesUL_Only_r15_29 = {
	"rohc-ProfilesUL-Only-r15",
	"rohc-ProfilesUL-Only-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_rohc_ProfilesUL_Only_r15_tags_29,
	sizeof(asn_DEF_rohc_ProfilesUL_Only_r15_tags_29)
		/sizeof(asn_DEF_rohc_ProfilesUL_Only_r15_tags_29[0]) - 1, /* 1 */
	asn_DEF_rohc_ProfilesUL_Only_r15_tags_29,	/* Same as above */
	sizeof(asn_DEF_rohc_ProfilesUL_Only_r15_tags_29)
		/sizeof(asn_DEF_rohc_ProfilesUL_Only_r15_tags_29[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_rohc_ProfilesUL_Only_r15_29,
	1,	/* Elements count */
	&asn_SPC_rohc_ProfilesUL_Only_r15_specs_29	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_rohc_ContextContinue_r15_value2enum_31[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_rohc_ContextContinue_r15_enum2value_31[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_rohc_ContextContinue_r15_specs_31 = {
	asn_MAP_rohc_ContextContinue_r15_value2enum_31,	/* "tag" => N; sorted by tag */
	asn_MAP_rohc_ContextContinue_r15_enum2value_31,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_rohc_ContextContinue_r15_tags_31[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_rohc_ContextContinue_r15_31 = {
	"rohc-ContextContinue-r15",
	"rohc-ContextContinue-r15",
	&asn_OP_NativeEnumerated,
	asn_DEF_rohc_ContextContinue_r15_tags_31,
	sizeof(asn_DEF_rohc_ContextContinue_r15_tags_31)
		/sizeof(asn_DEF_rohc_ContextContinue_r15_tags_31[0]) - 1, /* 1 */
	asn_DEF_rohc_ContextContinue_r15_tags_31,	/* Same as above */
	sizeof(asn_DEF_rohc_ContextContinue_r15_tags_31)
		/sizeof(asn_DEF_rohc_ContextContinue_r15_tags_31[0]), /* 2 */
	{ &asn_OER_type_rohc_ContextContinue_r15_constr_31, &asn_PER_type_rohc_ContextContinue_r15_constr_31, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_rohc_ContextContinue_r15_specs_31	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_outOfOrderDelivery_r15_value2enum_33[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_outOfOrderDelivery_r15_enum2value_33[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_outOfOrderDelivery_r15_specs_33 = {
	asn_MAP_outOfOrderDelivery_r15_value2enum_33,	/* "tag" => N; sorted by tag */
	asn_MAP_outOfOrderDelivery_r15_enum2value_33,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_outOfOrderDelivery_r15_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_outOfOrderDelivery_r15_33 = {
	"outOfOrderDelivery-r15",
	"outOfOrderDelivery-r15",
	&asn_OP_NativeEnumerated,
	asn_DEF_outOfOrderDelivery_r15_tags_33,
	sizeof(asn_DEF_outOfOrderDelivery_r15_tags_33)
		/sizeof(asn_DEF_outOfOrderDelivery_r15_tags_33[0]) - 1, /* 1 */
	asn_DEF_outOfOrderDelivery_r15_tags_33,	/* Same as above */
	sizeof(asn_DEF_outOfOrderDelivery_r15_tags_33)
		/sizeof(asn_DEF_outOfOrderDelivery_r15_tags_33[0]), /* 2 */
	{ &asn_OER_type_outOfOrderDelivery_r15_constr_33, &asn_PER_type_outOfOrderDelivery_r15_constr_33, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_outOfOrderDelivery_r15_specs_33	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_sn_SizeLo_r15_value2enum_35[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_sn_SizeLo_r15_enum2value_35[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_sn_SizeLo_r15_specs_35 = {
	asn_MAP_sn_SizeLo_r15_value2enum_35,	/* "tag" => N; sorted by tag */
	asn_MAP_sn_SizeLo_r15_enum2value_35,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_sn_SizeLo_r15_tags_35[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sn_SizeLo_r15_35 = {
	"sn-SizeLo-r15",
	"sn-SizeLo-r15",
	&asn_OP_NativeEnumerated,
	asn_DEF_sn_SizeLo_r15_tags_35,
	sizeof(asn_DEF_sn_SizeLo_r15_tags_35)
		/sizeof(asn_DEF_sn_SizeLo_r15_tags_35[0]) - 1, /* 1 */
	asn_DEF_sn_SizeLo_r15_tags_35,	/* Same as above */
	sizeof(asn_DEF_sn_SizeLo_r15_tags_35)
		/sizeof(asn_DEF_sn_SizeLo_r15_tags_35[0]), /* 2 */
	{ &asn_OER_type_sn_SizeLo_r15_constr_35, &asn_PER_type_sn_SizeLo_r15_constr_35, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sn_SizeLo_r15_specs_35	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_voice_r15_value2enum_37[] = {
	{ 0,	9,	"supported" }
};
static const unsigned int asn_MAP_voice_r15_enum2value_37[] = {
	0	/* supported(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_voice_r15_specs_37 = {
	asn_MAP_voice_r15_value2enum_37,	/* "tag" => N; sorted by tag */
	asn_MAP_voice_r15_enum2value_37,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_voice_r15_tags_37[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_voice_r15_37 = {
	"voice-r15",
	"voice-r15",
	&asn_OP_NativeEnumerated,
	asn_DEF_voice_r15_tags_37,
	sizeof(asn_DEF_voice_r15_tags_37)
		/sizeof(asn_DEF_voice_r15_tags_37[0]) - 1, /* 1 */
	asn_DEF_voice_r15_tags_37,	/* Same as above */
	sizeof(asn_DEF_voice_r15_tags_37)
		/sizeof(asn_DEF_voice_r15_tags_37[0]), /* 2 */
	{ &asn_OER_type_voice_r15_constr_37, &asn_PER_type_voice_r15_constr_37, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_voice_r15_specs_37	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PDCP_ParametersNR_r15_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15, rohc_Profiles_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_rohc_Profiles_r15_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rohc-Profiles-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct PDCP_ParametersNR_r15, rohc_ContextMaxSessions_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rohc_ContextMaxSessions_r15_12,
		0,
		{ 0, 0, 0 },
		&asn_DFL_12_cmp_4,	/* Compare DEFAULT 4 */
		&asn_DFL_12_set_4,	/* Set DEFAULT 4 */
		"rohc-ContextMaxSessions-r15"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDCP_ParametersNR_r15, rohc_ProfilesUL_Only_r15),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_rohc_ProfilesUL_Only_r15_29,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rohc-ProfilesUL-Only-r15"
		},
	{ ATF_POINTER, 4, offsetof(struct PDCP_ParametersNR_r15, rohc_ContextContinue_r15),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_rohc_ContextContinue_r15_31,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rohc-ContextContinue-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct PDCP_ParametersNR_r15, outOfOrderDelivery_r15),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_outOfOrderDelivery_r15_33,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"outOfOrderDelivery-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct PDCP_ParametersNR_r15, sn_SizeLo_r15),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sn_SizeLo_r15_35,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sn-SizeLo-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct PDCP_ParametersNR_r15, voice_r15),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_voice_r15_37,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"voice-r15"
		},
};
static const int asn_MAP_PDCP_ParametersNR_r15_oms_1[] = { 1, 3, 4, 5, 6 };
static const ber_tlv_tag_t asn_DEF_PDCP_ParametersNR_r15_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PDCP_ParametersNR_r15_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rohc-Profiles-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rohc-ContextMaxSessions-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rohc-ProfilesUL-Only-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rohc-ContextContinue-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* outOfOrderDelivery-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* sn-SizeLo-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* voice-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_PDCP_ParametersNR_r15_specs_1 = {
	sizeof(struct PDCP_ParametersNR_r15),
	offsetof(struct PDCP_ParametersNR_r15, _asn_ctx),
	asn_MAP_PDCP_ParametersNR_r15_tag2el_1,
	7,	/* Count of tags in the map */
	asn_MAP_PDCP_ParametersNR_r15_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PDCP_ParametersNR_r15 = {
	"PDCP-ParametersNR-r15",
	"PDCP-ParametersNR-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_PDCP_ParametersNR_r15_tags_1,
	sizeof(asn_DEF_PDCP_ParametersNR_r15_tags_1)
		/sizeof(asn_DEF_PDCP_ParametersNR_r15_tags_1[0]), /* 1 */
	asn_DEF_PDCP_ParametersNR_r15_tags_1,	/* Same as above */
	sizeof(asn_DEF_PDCP_ParametersNR_r15_tags_1)
		/sizeof(asn_DEF_PDCP_ParametersNR_r15_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PDCP_ParametersNR_r15_1,
	7,	/* Elements count */
	&asn_SPC_PDCP_ParametersNR_r15_specs_1	/* Additional specs */
};

