/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_RRCConnectionReconfigurationComplete_v15xy_IEs_H_
#define	_RRCConnectionReconfigurationComplete_v15xy_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCConnectionReconfigurationComplete-v15xy-IEs */
typedef struct RRCConnectionReconfigurationComplete_v15xy_IEs {
	OCTET_STRING_t	*scg_ConfigResponseNR_r15	/* OPTIONAL */;
	struct RRCConnectionReconfigurationComplete_v15xy_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionReconfigurationComplete_v15xy_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionReconfigurationComplete_v15xy_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionReconfigurationComplete_v15xy_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionReconfigurationComplete_v15xy_IEs_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionReconfigurationComplete_v15xy_IEs_H_ */
#include <asn_internal.h>
