/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_RRCConnectionReconfiguration_v15x0_IEs_H_
#define	_RRCConnectionReconfiguration_v15x0_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include "SubframeAssignment-r15.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCConnectionReconfiguration-v15x0-IEs */
typedef struct RRCConnectionReconfiguration_v15x0_IEs {
	struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15 {
		BOOLEAN_t	 scg_ConfigReleaseNR_r15;
		long	*sk_Counter_r15	/* OPTIONAL */;
		OCTET_STRING_t	*nr_SecondaryCellGroupConfig_r15	/* OPTIONAL */;
		OCTET_STRING_t	*nr_RadioBearerConfig_r15	/* OPTIONAL */;
		OCTET_STRING_t	*nr_RadioBearerConfigS_r15	/* OPTIONAL */;
		struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15__tdm_PatternSingle_Tx_r15 {
			SubframeAssignment_r15_t	 subframeAssignment_r15;
			long	*harq_Offset_r15	/* OPTIONAL */;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *tdm_PatternSingle_Tx_r15;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *endc_Config_r15;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionReconfiguration_v15x0_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionReconfiguration_v15x0_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionReconfiguration_v15x0_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionReconfiguration_v15x0_IEs_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionReconfiguration_v15x0_IEs_H_ */
#include <asn_internal.h>
