/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_RRCConnectionResume_v15x0_IEs_H_
#define	_RRCConnectionResume_v15x0_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RRCConnectionResume-v15x0-IEs */
typedef struct RRCConnectionResume_v15x0_IEs {
	long	*sk_Counter_r15	/* OPTIONAL */;
	OCTET_STRING_t	*nr_RadioBearerConfig_r15	/* OPTIONAL */;
	OCTET_STRING_t	*nr_RadioBearerConfigS_r15	/* OPTIONAL */;
	struct RRCConnectionResume_v15x0_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRCConnectionResume_v15x0_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RRCConnectionResume_v15x0_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionResume_v15x0_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_RRCConnectionResume_v15x0_IEs_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _RRCConnectionResume_v15x0_IEs_H_ */
#include <asn_internal.h>
