/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#include "RRCConnectionReconfiguration-v15x0-IEs.h"

static int
memb_harq_Offset_r15_constraint_8(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_sk_Counter_r15_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_harq_Offset_r15_constr_10 CC_NOTUSED = {
	{ 1, 1 }	/* (0..9) */,
	-1};
static asn_per_constraints_t asn_PER_memb_harq_Offset_r15_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  9 }	/* (0..9) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_sk_Counter_r15_constr_4 CC_NOTUSED = {
	{ 2, 1 }	/* (0..65535) */,
	-1};
static asn_per_constraints_t asn_PER_memb_sk_Counter_r15_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_tdm_PatternSingle_Tx_r15_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15__tdm_PatternSingle_Tx_r15, subframeAssignment_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SubframeAssignment_r15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"subframeAssignment-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15__tdm_PatternSingle_Tx_r15, harq_Offset_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_harq_Offset_r15_constr_10, &asn_PER_memb_harq_Offset_r15_constr_10,  memb_harq_Offset_r15_constraint_8 },
		0, 0, /* No default value */
		"harq-Offset-r15"
		},
};
static const int asn_MAP_tdm_PatternSingle_Tx_r15_oms_8[] = { 1 };
static const ber_tlv_tag_t asn_DEF_tdm_PatternSingle_Tx_r15_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_tdm_PatternSingle_Tx_r15_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* subframeAssignment-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* harq-Offset-r15 */
};
static asn_SEQUENCE_specifics_t asn_SPC_tdm_PatternSingle_Tx_r15_specs_8 = {
	sizeof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15__tdm_PatternSingle_Tx_r15),
	offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15__tdm_PatternSingle_Tx_r15, _asn_ctx),
	asn_MAP_tdm_PatternSingle_Tx_r15_tag2el_8,
	2,	/* Count of tags in the map */
	asn_MAP_tdm_PatternSingle_Tx_r15_oms_8,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_tdm_PatternSingle_Tx_r15_8 = {
	"tdm-PatternSingle-Tx-r15",
	"tdm-PatternSingle-Tx-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_tdm_PatternSingle_Tx_r15_tags_8,
	sizeof(asn_DEF_tdm_PatternSingle_Tx_r15_tags_8)
		/sizeof(asn_DEF_tdm_PatternSingle_Tx_r15_tags_8[0]) - 1, /* 1 */
	asn_DEF_tdm_PatternSingle_Tx_r15_tags_8,	/* Same as above */
	sizeof(asn_DEF_tdm_PatternSingle_Tx_r15_tags_8)
		/sizeof(asn_DEF_tdm_PatternSingle_Tx_r15_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_tdm_PatternSingle_Tx_r15_8,
	2,	/* Elements count */
	&asn_SPC_tdm_PatternSingle_Tx_r15_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_endc_Config_r15_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15, scg_ConfigReleaseNR_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"scg-ConfigReleaseNR-r15"
		},
	{ ATF_POINTER, 5, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15, sk_Counter_r15),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_sk_Counter_r15_constr_4, &asn_PER_memb_sk_Counter_r15_constr_4,  memb_sk_Counter_r15_constraint_2 },
		0, 0, /* No default value */
		"sk-Counter-r15"
		},
	{ ATF_POINTER, 4, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15, nr_SecondaryCellGroupConfig_r15),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-SecondaryCellGroupConfig-r15"
		},
	{ ATF_POINTER, 3, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15, nr_RadioBearerConfig_r15),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-RadioBearerConfig-r15"
		},
	{ ATF_POINTER, 2, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15, nr_RadioBearerConfigS_r15),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nr-RadioBearerConfigS-r15"
		},
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15, tdm_PatternSingle_Tx_r15),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_tdm_PatternSingle_Tx_r15_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tdm-PatternSingle-Tx-r15"
		},
};
static const int asn_MAP_endc_Config_r15_oms_2[] = { 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_endc_Config_r15_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_endc_Config_r15_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* scg-ConfigReleaseNR-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sk-Counter-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nr-SecondaryCellGroupConfig-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* nr-RadioBearerConfig-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* nr-RadioBearerConfigS-r15 */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* tdm-PatternSingle-Tx-r15 */
};
static asn_SEQUENCE_specifics_t asn_SPC_endc_Config_r15_specs_2 = {
	sizeof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15),
	offsetof(struct RRCConnectionReconfiguration_v15x0_IEs__endc_Config_r15, _asn_ctx),
	asn_MAP_endc_Config_r15_tag2el_2,
	6,	/* Count of tags in the map */
	asn_MAP_endc_Config_r15_oms_2,	/* Optional members */
	5, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_endc_Config_r15_2 = {
	"endc-Config-r15",
	"endc-Config-r15",
	&asn_OP_SEQUENCE,
	asn_DEF_endc_Config_r15_tags_2,
	sizeof(asn_DEF_endc_Config_r15_tags_2)
		/sizeof(asn_DEF_endc_Config_r15_tags_2[0]) - 1, /* 1 */
	asn_DEF_endc_Config_r15_tags_2,	/* Same as above */
	sizeof(asn_DEF_endc_Config_r15_tags_2)
		/sizeof(asn_DEF_endc_Config_r15_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_endc_Config_r15_2,
	6,	/* Elements count */
	&asn_SPC_endc_Config_r15_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RRCConnectionReconfiguration_v15x0_IEs_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RRCConnectionReconfiguration_v15x0_IEs, endc_Config_r15),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_endc_Config_r15_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"endc-Config-r15"
		},
};
static const int asn_MAP_RRCConnectionReconfiguration_v15x0_IEs_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_RRCConnectionReconfiguration_v15x0_IEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RRCConnectionReconfiguration_v15x0_IEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* endc-Config-r15 */
};
asn_SEQUENCE_specifics_t asn_SPC_RRCConnectionReconfiguration_v15x0_IEs_specs_1 = {
	sizeof(struct RRCConnectionReconfiguration_v15x0_IEs),
	offsetof(struct RRCConnectionReconfiguration_v15x0_IEs, _asn_ctx),
	asn_MAP_RRCConnectionReconfiguration_v15x0_IEs_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_RRCConnectionReconfiguration_v15x0_IEs_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RRCConnectionReconfiguration_v15x0_IEs = {
	"RRCConnectionReconfiguration-v15x0-IEs",
	"RRCConnectionReconfiguration-v15x0-IEs",
	&asn_OP_SEQUENCE,
	asn_DEF_RRCConnectionReconfiguration_v15x0_IEs_tags_1,
	sizeof(asn_DEF_RRCConnectionReconfiguration_v15x0_IEs_tags_1)
		/sizeof(asn_DEF_RRCConnectionReconfiguration_v15x0_IEs_tags_1[0]), /* 1 */
	asn_DEF_RRCConnectionReconfiguration_v15x0_IEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_RRCConnectionReconfiguration_v15x0_IEs_tags_1)
		/sizeof(asn_DEF_RRCConnectionReconfiguration_v15x0_IEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RRCConnectionReconfiguration_v15x0_IEs_1,
	1,	/* Elements count */
	&asn_SPC_RRCConnectionReconfiguration_v15x0_IEs_specs_1	/* Additional specs */
};

