/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_RS_ConfigSSB_NR_r15_H_
#define	_RS_ConfigSSB_NR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include "FreqOffsetNR-r15.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RS_ConfigSSB_NR_r15__subcarrierSpacingSSB_r15 {
	RS_ConfigSSB_NR_r15__subcarrierSpacingSSB_r15_kHz15	= 0,
	RS_ConfigSSB_NR_r15__subcarrierSpacingSSB_r15_kHz30	= 1,
	RS_ConfigSSB_NR_r15__subcarrierSpacingSSB_r15_kHz120	= 2,
	RS_ConfigSSB_NR_r15__subcarrierSpacingSSB_r15_kHz240	= 3
} e_RS_ConfigSSB_NR_r15__subcarrierSpacingSSB_r15;

/* Forward declarations */
struct MTC_SSB_NR_r15;

/* RS-ConfigSSB-NR-r15 */
typedef struct RS_ConfigSSB_NR_r15 {
	struct MTC_SSB_NR_r15	*measTimingConfig_r15	/* OPTIONAL */;
	FreqOffsetNR_r15_t	*offsetCenterFreq_r15	/* OPTIONAL */;
	long	*subcarrierSpacingSSB_r15	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RS_ConfigSSB_NR_r15_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_subcarrierSpacingSSB_r15_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RS_ConfigSSB_NR_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_RS_ConfigSSB_NR_r15_specs_1;
extern asn_TYPE_member_t asn_MBR_RS_ConfigSSB_NR_r15_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MTC-SSB-NR-r15.h"

#endif	/* _RS_ConfigSSB_NR_r15_H_ */
#include <asn_internal.h>
