/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_SCGFailureInformation_v15x0_IEs_H_
#define	_SCGFailureInformation_v15x0_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct FailureReportSCG_NR_r15;

/* SCGFailureInformation-v15x0-IEs */
typedef struct SCGFailureInformation_v15x0_IEs {
	struct FailureReportSCG_NR_r15	*failureReportSCG_NR_r15	/* OPTIONAL */;
	struct SCGFailureInformation_v15x0_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SCGFailureInformation_v15x0_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SCGFailureInformation_v15x0_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SCGFailureInformation_v15x0_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_SCGFailureInformation_v15x0_IEs_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "FailureReportSCG-NR-r15.h"

#endif	/* _SCGFailureInformation_v15x0_IEs_H_ */
#include <asn_internal.h>
