/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_SubCarrierSpacingNR_r15_H_
#define	_SubCarrierSpacingNR_r15_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SubCarrierSpacingNR-r15 */
typedef struct SubCarrierSpacingNR_r15 {
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SubCarrierSpacingNR_r15_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubCarrierSpacingNR_r15;
extern asn_SEQUENCE_specifics_t asn_SPC_SubCarrierSpacingNR_r15_specs_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SubCarrierSpacingNR_r15_H_ */
#include <asn_internal.h>
