/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EUTRA-RRC-Definitions"
 * 	found in "../lte-rrc/EUTRA-RRC-Definitions.asn"
 * 	`asn1c -gen-PER -no-gen-example -fcompound-names`
 */

#ifndef	_SystemInformationBlockType2_v10l0_IEs_H_
#define	_SystemInformationBlockType2_v10l0_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AdditionalSpectrumEmission-v10l0.h"
#include <constr_SEQUENCE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SystemInformationBlockType2-v10l0-IEs */
typedef struct SystemInformationBlockType2_v10l0_IEs {
	struct SystemInformationBlockType2_v10l0_IEs__freqInfo_v10l0 {
		AdditionalSpectrumEmission_v10l0_t	 additionalSpectrumEmission_v10l0;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} freqInfo_v10l0;
	struct SystemInformationBlockType2_v10l0_IEs__multiBandInfoList_v10l0 {
		A_SEQUENCE_OF(AdditionalSpectrumEmission_v10l0_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} multiBandInfoList_v10l0;
	struct SystemInformationBlockType2_v10l0_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SystemInformationBlockType2_v10l0_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SystemInformationBlockType2_v10l0_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_SystemInformationBlockType2_v10l0_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_SystemInformationBlockType2_v10l0_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SystemInformationBlockType2_v10l0_IEs_H_ */
#include <asn_internal.h>
